name: knnmodel

channels:
  - conda-forge

dependencies:
  - python=3.7
  - pip
  - setuptools
  - wheel
  - pandas
  - numpy
  - cloudpickle
  - scikit-learn
  - pyyaml
  - sphinx
  - pip:
    - nmslib # pip install --no-binary :all: nmslib
    - sphinx_rtd_theme